"""add fetch_cycles table

Revision ID: 85bd60da3b4d
Revises: 001
Create Date: 2026-03-20 10:35:44.706315
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '85bd60da3b4d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_scanned', sa.Integer(), nullable=False),
    sa.Column('total_passed', sa.Integer(), nullable=False),
    sa.Column('total_saved', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fetch_cycles')
    # ### end Alembic commands ###
